return {
  -- {
  --   "rachartier/tiny-code-action.nvim",
  --   dependencies = {
  --     { "nvim-lua/plenary.nvim" }, -- Required dependency
  --     { "nvim-telescope/telescope.nvim" }, -- Optional for Telescope integration
  --   },
  --   event = "LspAttach", -- Load only when an LSP server is attached
  --   config = function()
  --     require("tiny-code-action").setup({
  --       backend = "vim", -- Default backend; choose "delta" or "difftastic" if desired
  --       telescope_opts = {
  --         layout_strategy = "vertical",
  --         layout_config = {
  --           width = 0.7,
  --           height = 0.9,
  --         },
  --       },
  --       signs = {
  --         quickfix = { "??", { link = "DiagnosticInfo" } },
  --         refactor = { "?", { link = "DiagnosticWarning" } },
  --       },
  --     })
  --
  --     -- Keybinding to trigger code actions
  --     vim.keymap.set("n", "<leader>ca", function()
  --       require("tiny-code-action").code_action()
  --     end, { noremap = true, silent = true })
  --   end,
  -- },
}
